# Generated by Django 5.2.1 on 2025-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_recipient_bag_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='approval_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
