# Generated by Django 5.2.1 on 2025-06-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_donor_approval_notes_donor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='bag_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bag_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
